version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: kelly
      MYSQL_DATABASE: task_management_db
      MYSQL_USER: root
      MYSQL_PASSWORD: kelly
    volumes:
      - ./taskdumps.sql:/docker-entrypoint-initdb.d/taskdumps.sql
    ports:
      - "3306:3306"
