version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: kelly
      MYSQL_DATABASE: task_management_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
